# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10a75ae469ade7b77980374adc8c8c9332f8f09d5c21e5a053aa687f358945b9af797da2708f1d3a408433a61cf75838e3a8a22266336467230f91c43485c2ba

test:
  secret_key_base: d906ecadee6b97f87e5a25005e3a805b64a3668a1b4078fc8711e5591909fee29af3fbb26e88841cba660b34cbaedd1ea355ac21df4e03136c1c70fae5434b67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
